
package xportalserviceclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "XPortalWS", targetNamespace = "http://xportal.etranzact.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XPortalWS {


    /**
     * 
     * @param cardnum
     * @param mac
     * @param type
     * @param ipAddress
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "cardBlock_UnBlock_cardnum")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cardBlock_UnBlock_cardnum", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.CardBlockUnBlockCardnum")
    @ResponseWrapper(localName = "cardBlock_UnBlock_cardnumResponse", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.CardBlockUnBlockCardnumResponse")
    public String cardBlockUnBlockCardnum(
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "cardnum", targetNamespace = "")
        String cardnum,
        @WebParam(name = "ip_address", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param mac
     * @param type
     * @param ipAddress
     * @param mobile
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "cardBlock_UnBlock_mobile")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cardBlock_UnBlock_mobile", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.CardBlockUnBlockMobile")
    @ResponseWrapper(localName = "cardBlock_UnBlock_mobileResponse", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.CardBlockUnBlockMobileResponse")
    public String cardBlockUnBlockMobile(
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "mobile", targetNamespace = "")
        String mobile,
        @WebParam(name = "ip_address", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param cardnum
     * @param mac
     * @param ipAddress
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getCardHolderDetails_cardnum")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCardHolderDetails_cardnum", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.GetCardHolderDetailsCardnum")
    @ResponseWrapper(localName = "getCardHolderDetails_cardnumResponse", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.GetCardHolderDetailsCardnumResponse")
    public String getCardHolderDetailsCardnum(
        @WebParam(name = "cardnum", targetNamespace = "")
        String cardnum,
        @WebParam(name = "ip_address", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param mac
     * @param ipAddress
     * @param mobile
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getCardHolderDetails_mobile")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCardHolderDetails_mobile", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.GetCardHolderDetailsMobile")
    @ResponseWrapper(localName = "getCardHolderDetails_mobileResponse", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.GetCardHolderDetailsMobileResponse")
    public String getCardHolderDetailsMobile(
        @WebParam(name = "mobile", targetNamespace = "")
        String mobile,
        @WebParam(name = "ip_address", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param cardnum
     * @param mac
     * @param ipAddress
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "pinResetRequest_cardnum")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pinResetRequest_cardnum", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.PinResetRequestCardnum")
    @ResponseWrapper(localName = "pinResetRequest_cardnumResponse", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.PinResetRequestCardnumResponse")
    public String pinResetRequestCardnum(
        @WebParam(name = "cardnum", targetNamespace = "")
        String cardnum,
        @WebParam(name = "ip_address", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param mac
     * @param ipAddress
     * @param mobile
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "pinResetRequest_mobile")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pinResetRequest_mobile", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.PinResetRequestMobile")
    @ResponseWrapper(localName = "pinResetRequest_mobileResponse", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.PinResetRequestMobileResponse")
    public String pinResetRequestMobile(
        @WebParam(name = "mobile", targetNamespace = "")
        String mobile,
        @WebParam(name = "ip_address", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param cardnum
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "trial", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.Trial")
    @ResponseWrapper(localName = "trialResponse", targetNamespace = "http://xportal.etranzact.com/", className = "xportalserviceclient.TrialResponse")
    public List<Object> trial(
        @WebParam(name = "cardnum", targetNamespace = "")
        String cardnum);

}
