/*
package xportalserviceclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


*//**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 *//*
@WebServiceClient(name = "XPortalWSService", targetNamespace = "http://xportal.etranzact.com/", wsdlLocation = "http://localhost:8086/XPortalService/XPortalWS?wsdl")
public class XPortalWSService
    extends Service
{

    private final static URL XPORTALWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException XPORTALWSSERVICE_EXCEPTION;
    private final static QName XPORTALWSSERVICE_QNAME = new QName("http://xportal.etranzact.com/", "XPortalWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8086/XPortalService/XPortalWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        XPORTALWSSERVICE_WSDL_LOCATION = url;
        XPORTALWSSERVICE_EXCEPTION = e;
    }

    public XPortalWSService() {
        super(__getWsdlLocation(), XPORTALWSSERVICE_QNAME);
    }

    public XPortalWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), XPORTALWSSERVICE_QNAME, features);
    }

    public XPortalWSService(URL wsdlLocation) {
        super(wsdlLocation, XPORTALWSSERVICE_QNAME);
    }

    public XPortalWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, XPORTALWSSERVICE_QNAME, features);
    }

    public XPortalWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XPortalWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    *//**
     * 
     * @return
     *     returns XPortalWS
     *//*
    @WebEndpoint(name = "XPortalWSPort")
    public XPortalWS getXPortalWSPort() {
        return super.getPort(new QName("http://xportal.etranzact.com/", "XPortalWSPort"), XPortalWS.class);
    }

    *//**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XPortalWS
     *//*
    @WebEndpoint(name = "XPortalWSPort")
    public XPortalWS getXPortalWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xportal.etranzact.com/", "XPortalWSPort"), XPortalWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (XPORTALWSSERVICE_EXCEPTION!= null) {
            throw XPORTALWSSERVICE_EXCEPTION;
        }
        return XPORTALWSSERVICE_WSDL_LOCATION;
    }

}
*/