
package com.etranzact.supportmanager.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "securedsession", targetNamespace = "http://ws.webesa.etz.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Securedsession {


    /**
     * 
     * @param appid
     * @param checksum
     * @param sessionid
     * @param pan
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "invokesession", targetNamespace = "http://ws.webesa.etz.com/", className = "com.etranzact.supportmanager.client.Invokesession")
    @ResponseWrapper(localName = "invokesessionResponse", targetNamespace = "http://ws.webesa.etz.com/", className = "com.etranzact.supportmanager.client.InvokesessionResponse")
    public String invokesession(
        @WebParam(name = "appid", targetNamespace = "")
        String appid,
        @WebParam(name = "sessionid", targetNamespace = "")
        String sessionid,
        @WebParam(name = "pan", targetNamespace = "")
        String pan,
        @WebParam(name = "checksum", targetNamespace = "")
        String checksum);

    /**
     * 
     * @param appId
     * @param sessionId
     * @param answer
     * @param code
     * @param checksum
     * @param validateType
     * @param pan
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validatesession", targetNamespace = "http://ws.webesa.etz.com/", className = "com.etranzact.supportmanager.client.Validatesession")
    @ResponseWrapper(localName = "validatesessionResponse", targetNamespace = "http://ws.webesa.etz.com/", className = "com.etranzact.supportmanager.client.ValidatesessionResponse")
    public String validatesession(
        @WebParam(name = "appId", targetNamespace = "")
        String appId,
        @WebParam(name = "sessionId", targetNamespace = "")
        String sessionId,
        @WebParam(name = "pan", targetNamespace = "")
        String pan,
        @WebParam(name = "checksum", targetNamespace = "")
        String checksum,
        @WebParam(name = "code", targetNamespace = "")
        String code,
        @WebParam(name = "validateType", targetNamespace = "")
        int validateType,
        @WebParam(name = "answer", targetNamespace = "")
        String answer);

}
