
package com.etranzact.supportmanager.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "securedsessionService", targetNamespace = "http://ws.webesa.etz.com/", wsdlLocation = "http://172.16.10.101:8080/webconnectplus/securedsession?wsdl")
public class SecuredsessionService
    extends Service
{

    private final static URL SECUREDSESSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException SECUREDSESSIONSERVICE_EXCEPTION;
    private final static QName SECUREDSESSIONSERVICE_QNAME = new QName("http://ws.webesa.etz.com/", "securedsessionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {//APPESA
            url = new URL("http://172.16.10.101:8080/webconnectplus/securedsession?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SECUREDSESSIONSERVICE_WSDL_LOCATION = url;
        SECUREDSESSIONSERVICE_EXCEPTION = e;
    }

    public SecuredsessionService() {
        super(__getWsdlLocation(), SECUREDSESSIONSERVICE_QNAME);
    }

  

    public SecuredsessionService(URL wsdlLocation) {
        super(wsdlLocation, SECUREDSESSIONSERVICE_QNAME);
    }

    

    public SecuredsessionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

   

    /**
     * 
     * @return
     *     returns Securedsession
     */
    @WebEndpoint(name = "securedsessionPort")
    public Securedsession getSecuredsessionPort() {
        return super.getPort(new QName("http://ws.webesa.etz.com/", "securedsessionPort"), Securedsession.class);
    }

    

    private static URL __getWsdlLocation() {
        if (SECUREDSESSIONSERVICE_EXCEPTION!= null) {
            throw SECUREDSESSIONSERVICE_EXCEPTION;
        }
        return SECUREDSESSIONSERVICE_WSDL_LOCATION;
    }

}
