
package com.etz.webserviceClient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2-hudson-752-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "XPortalWS", targetNamespace = "http://xportal.etranzact.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XPortalWS {


    /**
     * 
     * @param cardnum
     * @param mac
     * @param type
     * @param ipAddress
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "cardBlock_UnBlock_cardnum")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cardBlock_UnBlock_cardnum", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.CardBlockUnBlockCardnum")
    @ResponseWrapper(localName = "cardBlock_UnBlock_cardnumResponse", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.CardBlockUnBlockCardnumResponse")
    public String cardBlockUnBlockCardnum(
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "cardnum", targetNamespace = "")
        String cardnum,
        @WebParam(name = "ip_address", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param mac
     * @param type
     * @param ipAddress
     * @param mobile
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "cardBlock_UnBlock_mobile")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cardBlock_UnBlock_mobile", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.CardBlockUnBlockMobile")
    @ResponseWrapper(localName = "cardBlock_UnBlock_mobileResponse", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.CardBlockUnBlockMobileResponse")
    public String cardBlockUnBlockMobile(
        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "mobile", targetNamespace = "")
        String mobile,
        @WebParam(name = "ip_address", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param phone
     * @param cardnum
     * @param street
     * @param state
     * @param lastname
     * @param firstname
     * @param country
     * @param city
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cardDetailsUpdate", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.CardDetailsUpdate")
    @ResponseWrapper(localName = "cardDetailsUpdateResponse", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.CardDetailsUpdateResponse")
    public String cardDetailsUpdate(
        @WebParam(name = "cardnum", targetNamespace = "")
        String cardnum,
        @WebParam(name = "lastname", targetNamespace = "")
        String lastname,
        @WebParam(name = "firstname", targetNamespace = "")
        String firstname,
        @WebParam(name = "phone", targetNamespace = "")
        String phone,
        @WebParam(name = "street", targetNamespace = "")
        String street,
        @WebParam(name = "city", targetNamespace = "")
        String city,
        @WebParam(name = "state", targetNamespace = "")
        String state,
        @WebParam(name = "country", targetNamespace = "")
        String country);

    /**
     * 
     * @param mac
     * @param ipAddress
     * @param mobile
     * @return
     *     returns com.etz.webserviceClient.CardHolder
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCardHolderDetailsByMobile", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.GetCardHolderDetailsByMobile")
    @ResponseWrapper(localName = "getCardHolderDetailsByMobileResponse", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.GetCardHolderDetailsByMobileResponse")
    public CardHolder getCardHolderDetailsByMobile(
        @WebParam(name = "mobile", targetNamespace = "")
        String mobile,
        @WebParam(name = "ipAddress", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param cardnum
     * @param mac
     * @param ipAddress
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getCardHolderDetails_cardnum")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCardHolderDetails_cardnum", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.GetCardHolderDetailsCardnum")
    @ResponseWrapper(localName = "getCardHolderDetails_cardnumResponse", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.GetCardHolderDetailsCardnumResponse")
    public String getCardHolderDetailsCardnum(
        @WebParam(name = "cardnum", targetNamespace = "")
        String cardnum,
        @WebParam(name = "ip_address", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param mac
     * @param ipAddress
     * @param mobile
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "getCardHolderDetails_mobile")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCardHolderDetails_mobile", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.GetCardHolderDetailsMobile")
    @ResponseWrapper(localName = "getCardHolderDetails_mobileResponse", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.GetCardHolderDetailsMobileResponse")
    public String getCardHolderDetailsMobile(
        @WebParam(name = "mobile", targetNamespace = "")
        String mobile,
        @WebParam(name = "ip_address", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param cardnum
     * @param mac
     * @param ipAddress
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "pinResetRequest_cardnum")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pinResetRequest_cardnum", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.PinResetRequestCardnum")
    @ResponseWrapper(localName = "pinResetRequest_cardnumResponse", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.PinResetRequestCardnumResponse")
    public String pinResetRequestCardnum(
        @WebParam(name = "cardnum", targetNamespace = "")
        String cardnum,
        @WebParam(name = "ip_address", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param mac
     * @param ipAddress
     * @param mobile
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "pinResetRequest_mobile")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pinResetRequest_mobile", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.PinResetRequestMobile")
    @ResponseWrapper(localName = "pinResetRequest_mobileResponse", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.PinResetRequestMobileResponse")
    public String pinResetRequestMobile(
        @WebParam(name = "mobile", targetNamespace = "")
        String mobile,
        @WebParam(name = "ip_address", targetNamespace = "")
        String ipAddress,
        @WebParam(name = "mac", targetNamespace = "")
        String mac);

    /**
     * 
     * @param amount
     * @param compId
     * @param phone
     * @param depotId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "processDirectDebit", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.ProcessDirectDebit")
    @ResponseWrapper(localName = "processDirectDebitResponse", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.ProcessDirectDebitResponse")
    public String processDirectDebit(
        @WebParam(name = "amount", targetNamespace = "")
        String amount,
        @WebParam(name = "phone", targetNamespace = "")
        String phone,
        @WebParam(name = "compId", targetNamespace = "")
        String compId,
        @WebParam(name = "depotId", targetNamespace = "")
        String depotId);

    /**
     * 
     * @param cardnum
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "trial", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.Trial")
    @ResponseWrapper(localName = "trialResponse", targetNamespace = "http://xportal.etranzact.com/", className = "com.etz.webserviceClient.TrialResponse")
    public List<Object> trial(
        @WebParam(name = "cardnum", targetNamespace = "")
        String cardnum);

}
